name: CI
on:
  pull_request:
  push:

jobs:
  lint:
    uses: nathanwn/workflows/.github/workflows/tox.yml@54c16bafa9c75cad9db4d716354fefa87b3cb09b  # v0.6.0
    with:
      os: '["ubuntu-latest"]'
      env: '["pre-commit"]'

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - name: Run tests
        run: npm run test
      # TODO: When node-tree-sitter resolve their issues, upgrade and renable this
      # https://github.com/tree-sitter/node-tree-sitter/issues/244
      # - run: npm run test_node_bindings
      - name: Run regression test
        run: npm run test_regression
