name: CI
on:
  pull_request:
  push:

jobs:
  lint:
    uses: nathanwn/workflows/.github/workflows/tox.yml@54c16bafa9c75cad9db4d716354fefa87b3cb09b  # v0.6.0
    with:
      os: '["ubuntu-latest"]'
      env: '["pre-commit"]'

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - name: Benchmark test
        run: npm run benchmark-test
